version: '3'

services:
  roach1:
    image: cockroachdb/cockroach
    ports:
      - "8080:8080"
      - "26257:26257"
    networks:
      - roach_net
    command: start --insecure
    volumes:
       - roach1_data:/cockroach/cockroach-data
  roach2:
    image: cockroachdb/cockroach
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - roach2_data:/cockroach/cockroach-data
  roach3:
    image: cockroachdb/cockroach
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - roach3_data:/cockroach/cockroach-data
  roach4:
    image: cockroachdb/cockroach
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - roach4_data:/cockroach/cockroach-data
  roach5:
    image: cockroachdb/cockroach
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - roach5_data:/cockroach/cockroach-data
  roach6:
    image: cockroachdb/cockroach
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - roach6_data:/cockroach/cockroach-data
  roach7:
    image: cockroachdb/cockroach
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - roach7_data:/cockroach/cockroach-data
  roach8:
    image: cockroachdb/cockroach
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - roach8_data:/cockroach/cockroach-data
  roach9:
    image: cockroachdb/cockroach
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - roach9_data:/cockroach/cockroach-data
networks:
  roach_net:
volumes:
  roach1_data:
  roach2_data:
  roach3_data:
  roach4_data:
  roach5_data:
  roach6_data:
  roach7_data:
  roach8_data:
  roach9_data: