version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  roach1:
    image: cockroachdb/cockroach
    restart: always
    ports:
      - "8080:8080"
      - "26257:26257"
    networks:
      - roach_net
    command: start --insecure
    volumes:
       - ./data/roach1:/cockroach/cockroach-data
  roach2:
    image: cockroachdb/cockroach
    restart: always
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - ./data/roach2:/cockroach/cockroach-data
  roach3:
    image: cockroachdb/cockroach
    restart: always
    networks:
      - roach_net
    command: start --insecure --join=roach1
    volumes:
       - ./data/roach3:/cockroach/cockroach-data
networks:
  roach_net:
